name: flutter_atomic_state
description: |
  A Flutter package providing widgets for global application immutable atomically updated states.
version: 0.1.3
homepage: https://github.com/quantu-app/dart-flutter_atomic_state
repository: https://github.com/quantu-app/dart-flutter_atomic_state

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  atomic_state: "^0.1.2"
  meta: "^1.1.8"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
